name: E2E Tests

on:
  pull_request:
    branches:
      - main

  schedule:
    - cron: '40 7 * * *'
      displayName: Everyday check
      branches:
        include:
          - main

  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: ''

jobs:
  E2E_Windows_Edge_Test:
    runs-on: windows-latest
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        continue-on-error: true
        run: mvn test "-Dbroswer=edge" "-Dheadless=false" "-Dtest=${{ github.event.inputs.testsPath }}"

      - name: Allure Report
        run: mvn allure:report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows_Edge
          path: target/site/allure-maven-plugin/index.html

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

  E2E_Ubuntu_Chrome_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        continue-on-error: true
        run: mvn test "-Dbroswer=chrome" "-Dheadless=headless" "-Dtest=${{ github.event.inputs.testsPath }}"

      - name: Allure Report
        run: mvn allure:report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Ubuntu_Chrome
          path: target/site/allure-maven-plugin/index.html

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit